name: Lint - Biome

on:
  push:
    branches:
      - master
      - insider
    paths:
      - "font-size/**"
      - "product.json"
      - "announcements-*.json"
      - "upstream/*.json"
      - "patches/*.json"
      - ".github/workflows/biome.yml"
  pull_request:
    branches:
      - "**"
    paths:
      - "font-size/**"
      - "product.json"
      - "announcements-*.json"
      - "upstream/*.json"
      - "patches/*.json"
      - ".github/workflows/biome.yml"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  biome:
    name: Biome
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc

      - name: Install Biome
        run: npm install --no-save @biomejs/biome

      - name: Run Biome lint
        run: npx @biomejs/biome check . --write --no-errors-on-unmatched

      - name: Run Biome format check
        run: npx @biomejs/biome format . --write --no-errors-on-unmatched
