name: Moderation - Lock Closed Threads

on:
  schedule:
    - cron: 0 2 * * *

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@b2726a6ae6f1e1b06eb0ff28f7e4fb5e4246bbca # v6.0.2
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: "90"
          pr-inactive-days: "90"
          discussion-inactive-days: "90"
          log-output: true
